/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ErrorDialog: typeof import('./components/ErrorDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    MainBackground: typeof import('./components/MainBackground.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCard: typeof import('./components/UserCard.vue')['default']
    UserCreateForm: typeof import('./components/UserCreateForm.vue')['default']
    UserDetailsCard: typeof import('./components/UserDetailsCard.vue')['default']
    UserUpdateForm: typeof import('./components/UserUpdateForm.vue')['default']
  }
}
